# Default middleware templates
middlewares:
  - id: authelia
    name: Authelia
    type: forwardAuth
    config:
      address: "http://authelia:9091/api/authz/forward-auth"
      trustForwardHeader: true
      authResponseHeaders:
        - "Remote-User"
        - "Remote-Groups"
        - "Remote-Name"
        - "Remote-Email"

  - id: authentik
    name: Authentik
    type: forwardAuth
    config:
      address: "http://authentik:9000/outpost.goauthentik.io/auth/traefik"
      trustForwardHeader: true
      authResponseHeaders:
        - "X-authentik-username"
        - "X-authentik-groups"
        - "X-authentik-email"
        - "X-authentik-name"
        - "X-authentik-uid"

  - id: basic-auth
    name: Basic Auth
    type: basicAuth
    config:
      users:
        - "admin:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/"

  - id: jwt-auth
    name: JWT Authentication
    type: forwardAuth
    config:
      address: "http://jwt-auth:8080/verify"
      trustForwardHeader: true
      authResponseHeaders:
        - "X-JWT-Sub"
        - "X-JWT-Name"
        - "X-JWT-Email"

  - id: ip-whitelist
    name: IP Whitelist
    type: ipWhiteList
    config:
      sourceRange:
        - "127.0.0.1/32"
        - "192.168.1.0/24"
        - "10.0.0.0/8"

  - id: rate-limit
    name: Rate Limit
    type: rateLimit
    config:
      average: 100
      burst: 50

  - id: security-chain
    name: Security Chain
    type: chain
    config:
      middlewares:
        - rate-limit
        - ip-whitelist

  - id: headers-standard
    name: Standard Security Headers
    type: headers
    config:
      accessControlAllowMethods:
        - GET
        - OPTIONS
        - PUT
      browserXssFilter: true
      contentTypeNosniff: true
      customFrameOptionsValue: SAMEORIGIN
      customResponseHeaders:
        X-Forwarded-Proto: https
        X-Robots-Tag: none,noarchive,nosnippet,notranslate,noimageindex
        server: ""
      forceSTSHeader: true
      hostsProxyHeaders:
        - X-Forwarded-Host
      permissionsPolicy: camera=(), microphone=(), geolocation=(), payment=(), usb=(), vr=()
      referrerPolicy: same-origin
      sslProxyHeaders:
        X-Forwarded-Proto: https
      stsIncludeSubdomains: true
      stsPreload: true
      stsSeconds: 63072000
      
  - id: nextcloud-dav
    name: Nextcloud WebDAV Redirect
    type: replacepathregex
    config:
      regex: "^/.well-known/ca(l|rd)dav"
      replacement: "/remote.php/dav/"
  
# Plugin middleware templates
  - id: "geoblock"
    name: "Geoblock"
    type: "plugin"
    config:
      geoblock:
        silentStartUp: false
        allowLocalRequests: false
        logLocalRequests: false
        logAllowedRequests: false
        logApiRequests: false
        api: "https://get.geojs.io/v1/ip/country/{ip}"
        apiTimeoutMs: 750
        cacheSize: 15
        forceMonthlyUpdate: false
        allowUnknownCountries: false
        unknownCountryApiResponse: "nil"
        blackListMode: false
        addCountryHeader: false
        countries:
          - DE

  - id: "crowdsec"
    name: "Crowdsec"
    type: "plugin"
    config:
      crowdsec:
        enabled: true # Enable CrowdSec plugin
        logLevel: INFO # Log level
        updateIntervalSeconds: 15 # Update interval
        updateMaxFailure: 0 # Update max failure
        defaultDecisionSeconds: 15 # Default decision seconds
        httpTimeoutSeconds: 10 # HTTP timeout
        crowdsecMode: live # CrowdSec mode
        crowdsecAppsecEnabled: true # Enable AppSec
        crowdsecAppsecHost: crowdsec:7422 # CrowdSec IP address which you noted down later
        crowdsecAppsecFailureBlock: true # Block on failure
        crowdsecAppsecUnreachableBlock: true # Block on unreachable
        crowdsecAppsecBodyLimit: 10485760
        crowdsecLapiKey: "PUT_YOUR_BOUNCER_KEY_HERE_OR_IT_WILL_NOT_WORK" # CrowdSec API key which you noted down later
        crowdsecLapiHost: crowdsec:8080 # CrowdSec  
        crowdsecLapiScheme: http # CrowdSec API scheme
        forwardedHeadersTrustedIPs: # Forwarded headers trusted IPs
          - "0.0.0.0/0" # All IP addresses are trusted for forwarded headers
        clientTrustedIPs: # Client trusted IPs
          - "10.0.0.0/8" # Internal LAN IP addresses
          - "172.16.0.0/12" # Internal LAN IP addresses
          - "192.168.0.0/16" # Internal LAN IP addresses
          - "100.89.137.0/20" # Internal LAN IP addresses
