name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - master
      - dev
    paths:
      - 'Dockerfile'
      - 'go.mod'
      - 'go.sum'
      - 'main.go'
      - 'Makefile'
      - '.github/workflows/**'
      - 'api/**'
      - 'config/**'
      - 'database/**'
      - 'models/**'
      - 'services/**'
      - 'ui/**'
    tags:
      - 'v*'
  workflow_dispatch:

env:
  DOCKERHUB_IMAGE_NAME: hhftechnology/middleware-manager

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug trigger
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Ref name: ${{ github.ref_name }}"
          echo "Branch: ${{ github.ref_type == 'branch' && github.ref_name || 'not a branch' }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=semver,pattern={{major}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=ref,event=branch,enable=${{ github.ref_type == 'branch' && github.ref_name != 'dev' }}
            type=raw,value=dev,enable=${{ github.ref_name == 'dev' }}
            type=sha,format=short,enable=${{ github.ref_type == 'branch' }}
            type=raw,value=latest,enable=${{ github.ref_name == 'main' || github.ref_name == 'master' }}

      - name: Debug tags
        run: echo "Tags: ${{ steps.meta.outputs.tags }}"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}